os: ubuntu
dist: disco
language: node_js
node_js:
  - "12"
install:
  - yarn global add @electron-forge/cli
  - yarn
script:
  - electron-forge make --platform=linux --arch=all
  - electron-forge make --platform=darwin --arch=all
  - electron-forge make --platform=mas --arch=all
  - electron-forge make --platform=win32 --arch=all
