sudo: required
matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    language: node_js
    node_js: '12'
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    addons:
      homebrew:
        packages:
          - docker
cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
script:
- docker run --rm \
      -v ${PWD}:/project \
      -v ~/.cache/electron:/root/.cache/electron \
      -v ~/.cache/electron-builder:/root/.cache/electron-builder \
      electronuserland/builder:wine \
      /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn build --linux --win"
- yarn lint
- yarn build

before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  api_key:
    secure: gQMNuaffkJlpdPKz5Q5zpHntLMhGw44nb7faoqh25ISj4INzLelEnF8qONfO31aFbd80/qycWB4GdhkjvNXl1gvfyg6zEGvGppGMZWg9JBuXxkOK+QZYDUtfXa8SGlYrhbsnKDsTvNu4hbkp9nGHmmn3TOIUorKGQdFUXfMiuuAtN5lvocuNBt/S6qT0CXac/2+XAIGpAf+X5rF432HFfSXcDcX7Smxw+wBq3ETmzQaMFzEqEA5E4Y11TEmJ77r/RTWR9QMFW+WUtmXjpT6n6Ap9tbv1RAcV/o7PPfNXUz9Qw/vv6S5zWPPRwahfNNpBI6Xo3OoHIMMbnzl9UTCDF8CpJO/rjmyhxQWiJ5SgJ3+ujLnMN+5u/dImfLC7hsi6hD+Fz8SJnu9Zo8FQvDBae3eg0bPw93g52CMGHq/A3RGmIzCjsuaRxi5t2GOTBsOESIo3udRHvxTTg7xSuCfR9jrQiszpXwzMnvhsIpzVNq+qO4MO2PBoZKRPAuM+sFXOz8IooQLaI8ZXyx5BaandBa4ndmhHvVmorv9JPJf97PfmZ2RP2bgloSdufm2RexHAAKR3Ne/ejptT6LA95MHJQWdwhGUZpbaFIA72QIfFKop4NlVJkmlXPsvsCzz+txnBI1XLr/+2JCMtNudqvog+kIruBy/pmZ0lnvPdA5OrTDA=
  file:
    - release/day-counter-mac.zip
    - release/day-counter-mac.dmg
    - release/day-counter-mac.dmg.blockmap
    - release/day-counter-linux.snap
    - release/day-counter-linux.zip
    - release/day-counter-win.exe
    - release/day-counter-win.exe.blockmap
  on:
    repo: wnuke/day-counter
