os: ubuntu
dist: disco
language: node_js
before_install:
  - sudo apt-get install curl python-software-properties
  - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  - sudo apt-get install nodejs yarn
  - sudo npm i -g electron-forge
script:
  - electron-forge make --platform=linux --arch=all
  - electron-forge make --platform=darwin --arch=all
  - electron-forge make --platform=mas --arch=all
  - electron-forge make --platform=win32 --arch=all
