os: ubuntu
dist: disco
language: node_js
install:
  - sudo apt-get install curl python-software-properties
  - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update
  - sudo apt-get install nodejs yarn
  - sudo npm i -g electron-forge
  - sudo npm i -g yarn
  - yarn
script:
  - electron-forge make --platform=linux --arch=all
  - electron-forge make --platform=darwin --arch=all
  - electron-forge make --platform=mas --arch=all
  - electron-forge make --platform=win32 --arch=all
